import Head from "next/head"
import Header from "../components/Header"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rhino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rhino-logo.jpg" />
      </Head>

      {/* Header */}
      <Header />
      {/* Navbar */}
      {/* Results */}
    </div>
  )
}
